const mongoose = require("mongoose");

/**
 * LOT NUMBER REGISTRY — one document per lot number a company has issued.
 *
 * Why a separate collection rather than a unique index on Inventory.lotNumber:
 * an Inventory row is per (product, owner, WAREHOUSE, batch), so ONE lot legally
 * occupies several rows — a warehouse→warehouse transfer copies the source's lot
 * identity into the destination row, and a company→seller supply mirrors it onto
 * the seller's row. A unique index on Inventory.lotNumber would reject both and
 * break CLAUDE.md invariant #3. This registry holds exactly one row per issued
 * number, so the unique index below is the real guarantee that a lot number is
 * never handed out twice.
 *
 * Registered for lots MINTED through the Create Lot / Receive Lot flow (see
 * lotService.receiveLot); GRN postings carry supplier-provided lot codes and are
 * left alone.
 */
const lotNumberSchema = new mongoose.Schema(
  {
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      index: true,
    },

    // The issued number, normalised to trimmed uppercase so "ab-1" and "AB-1"
    // can never both be handed out.
    lotNumber: {
      type: String,
      required: true,
      uppercase: true,
      trim: true,
    },

    // The product this number belongs to. Re-receiving stock into the SAME lot
    // of the SAME product is legitimate (it's one lot, topped up); the same
    // number for a DIFFERENT product is the duplicate we reject.
    productId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product",
      required: true,
    },

    // "khetify" — generated by lotNumberService; "manual" — typed by the operator.
    source: {
      type: String,
      enum: ["khetify", "manual"],
      default: "manual",
    },

    // The per (company, product) running serial baked into a generated number.
    // Null for manual numbers.
    serial: { type: Number, default: null },
  },
  { timestamps: true }
);

// THE uniqueness guarantee. Company-scoped, matching the multi-tenancy rule —
// and a generated number already embeds the company code, so cross-tenant
// collisions are impossible by construction anyway.
lotNumberSchema.index({ companyId: 1, lotNumber: 1 }, { unique: true });

module.exports = mongoose.model("LotNumber", lotNumberSchema);
