const mongoose = require("mongoose");
const Company = require("../model/Company/Company");
const Product = require("../model/Company/productModel");
const Warehouse = require("../model/Warehouse/Warehouse");
const Inventory = require("../model/Inventory/Inventory");
const Location = require("../model/Warehouse/Location");
const Order = require("../model/Order/Order");
const UnitSerial = require("../model/Barcode/UnitSerial");
const svc = require("../services/barcodeService");

let companyId, warehouseId, productId, inv;

beforeEach(async () => {
  const c = await Company.create({ fullName: "Co", email: `c-${new mongoose.Types.ObjectId()}@x.com`, password: "x" });
  companyId = c._id;
  const wh = await Warehouse.create({ companyId, name: "Main", code: "WH1" });
  warehouseId = wh._id;
  const p = await Product.create({ companyId, productName: "Urea", skuNumber: "U1" });
  productId = p._id;
  inv = await Inventory.create({ productId, ownerType: "company", ownerId: companyId, warehouseId, batchNumber: "B1", lotNumber: "LOT1", offlineStock: 100, availableStock: 100 });
});

describe("generateUnits() uniqueness", () => {
  test("generates the requested count with all-unique serials and flags the product", async () => {
    const r = await svc.generateUnits(companyId, inv._id, 50);
    expect(r.generated).toBe(50);

    const serials = await UnitSerial.find({ companyId, inventoryId: inv._id }).distinct("serial");
    expect(serials).toHaveLength(50); // distinct === count → no duplicates

    const prod = await Product.findById(productId);
    expect(prod.trackSerial).toBe(true);
  });

  test("a second batch continues the sequence without collision", async () => {
    await svc.generateUnits(companyId, inv._id, 50);
    await svc.generateUnits(companyId, inv._id, 40);
    const count = await UnitSerial.countDocuments({ companyId, inventoryId: inv._id });
    const distinct = (await UnitSerial.find({ companyId, inventoryId: inv._id }).distinct("serial")).length;
    expect(count).toBe(90);
    expect(distinct).toBe(90);
  });

  test("refuses to generate more unit labels than the lot's available stock", async () => {
    // inv has availableStock 100; label 90, then try 20 more → 110 > 100
    await svc.generateUnits(companyId, inv._id, 90);
    await expect(svc.generateUnits(companyId, inv._id, 20)).rejects.toMatchObject({ status: 409 });
    // count is unchanged — nothing was generated by the rejected call
    const count = await UnitSerial.countDocuments({ companyId, inventoryId: inv._id });
    expect(count).toBe(90);
  });

  test("the unique index rejects a duplicate serial", async () => {
    await svc.generateUnits(companyId, inv._id, 1);
    const dup = await UnitSerial.findOne({ companyId, inventoryId: inv._id });
    await expect(
      UnitSerial.create({ companyId, serial: dup.serial, productId, inventoryId: inv._id, lotNumber: "LOT1" })
    ).rejects.toBeTruthy();
  });
});

describe("unitSerial() format", () => {
  test("is prefix-less: <LOTKEY>-<3-digit seq>, non-alphanumerics stripped", () => {
    expect(svc.unitSerial("AB-SAM-IO-012", 1)).toBe("ABSAMIO012-001");
    expect(svc.unitSerial("UR-2026-JUN-001", 50)).toBe("UR2026JUN001-050");
  });
});

describe("resolveScan() dispatch", () => {
  test("resolves a unit by its bare serial AND a legacy K-U- prefixed scan", async () => {
    await svc.generateUnits(companyId, inv._id, 1);
    const bare = (await UnitSerial.findOne({ companyId, inventoryId: inv._id })).serial;
    expect(bare).not.toMatch(/^K-U-/i); // stored bare now

    const fresh = await svc.resolveScan(companyId, bare, "company_admin");
    expect(fresh.type).toBe("unit");
    expect(fresh.unit.serial).toBe(bare);

    // an old physical label still carrying the prefix resolves to the same unit
    const legacy = await svc.resolveScan(companyId, `K-U-${bare}`, "company_admin");
    expect(legacy.type).toBe("unit");
    expect(legacy.unit.serial).toBe(bare);
  });

  test("routes unit / location / raw-lot codes to the right type", async () => {
    await svc.generateUnits(companyId, inv._id, 2);
    const aSerial = (await UnitSerial.findOne({ companyId, inventoryId: inv._id })).serial;
    const bin = await Location.create({ companyId, warehouseId, type: "bin", code: "A1", fullCode: "WH1-A-A1", barcode: "WH1-A-A1" });

    const u = await svc.resolveScan(companyId, aSerial, "company_admin");
    expect(u.type).toBe("unit");

    const l = await svc.resolveScan(companyId, "WH1-A-A1", "company_admin");
    expect(l.type).toBe("location");
    expect(String(l.location._id)).toBe(String(bin._id));

    const lot = await svc.resolveScan(companyId, "LOT1", "company_admin");
    expect(lot.type).toBe("lot");
    expect(lot.rows[0].lotNumber).toBe("LOT1");

    await expect(svc.resolveScan(companyId, "NONSENSE-XYZ", "company_admin")).rejects.toMatchObject({ status: 404 });
  });

  test("next actions are role-aware (operator can putaway a generated unit; auditor cannot)", async () => {
    // A lot ALREADY placed in a warehouse mints its units straight into stock,
    // so there is nothing to put away — the next action there is picking.
    await svc.generateUnits(companyId, inv._id, 1);
    const stocked = await UnitSerial.findOne({ companyId, inventoryId: inv._id });
    expect(stocked.status).toBe("in_stock");
    expect((await svc.resolveScan(companyId, stocked.serial, "warehouse_operator")).nextActions).not.toContain("putaway");

    // A lot that has NOT been placed in a warehouse yet mints "generated" units
    // — those are the ones awaiting putaway.
    const unplaced = await Inventory.create({
      productId, ownerType: "company", ownerId: companyId,
      batchNumber: "B2", lotNumber: "LOT2", offlineStock: 10, availableStock: 10,
    });
    await svc.generateUnits(companyId, unplaced._id, 1);
    const awaiting = await UnitSerial.findOne({ companyId, inventoryId: unplaced._id });
    expect(awaiting.status).toBe("generated");

    const op = await svc.resolveScan(companyId, awaiting.serial, "warehouse_operator");
    expect(op.nextActions).toContain("putaway");
    const aud = await svc.resolveScan(companyId, awaiting.serial, "auditor");
    expect(aud.nextActions).not.toContain("putaway");
  });
});

describe("recall() distribution", () => {
  test("recalls not-sold units, leaves sold ones, and reports stock + customers", async () => {
    await svc.generateUnits(companyId, inv._id, 5);
    const all = await UnitSerial.find({ companyId, inventoryId: inv._id }).sort({ serial: 1 });

    // simulate: 2 in stock, 1 sold (with order), rest generated
    const order = await Order.create({ companyId, orderNumber: "O-1", customerName: "Ramesh Traders" });
    await UnitSerial.updateOne({ _id: all[0]._id }, { $set: { status: "in_stock" } });
    await UnitSerial.updateOne({ _id: all[1]._id }, { $set: { status: "in_stock" } });
    await UnitSerial.updateOne({ _id: all[2]._id }, { $set: { status: "sold", orderId: order._id } });

    const r = await svc.recall(companyId, "LOT1", { performedBy: new mongoose.Types.ObjectId() });

    expect(r.soldUnits).toBe(1);
    expect(r.recalledUnits).toBe(4); // 5 total − 1 sold
    expect(r.customers).toHaveLength(1);
    expect(r.customers[0].customerName).toBe("Ramesh Traders");
    expect(r.stock[0].availableStock).toBe(100); // quantity ledger reported

    // sold unit kept; others recalled
    const sold = await UnitSerial.findById(all[2]._id);
    expect(sold.status).toBe("sold");
    const recalled = await UnitSerial.findById(all[0]._id);
    expect(recalled.status).toBe("recalled");
  });
});
