/**
 * UNIT LABELS AT LOT CREATION — for a SINGLE-PACKAGE lot too.
 *
 * A boxed lot came out of Create Lot fully labelled; a single-package one came
 * out with nothing, and the Labels page opened on "0 of 10 unit(s) already
 * labelled" until someone pressed Generate. The minting was gated on the
 * packaging object, which is null when bulk packaging is off — nothing about how
 * a lot is packed decides whether its units deserve an identity.
 *
 * These pin both shapes coming out labelled, by the same rule and in the same
 * format the manual button produces.
 */
const mongoose = require("mongoose");
const Company = require("../model/Company/Company");
const Product = require("../model/Company/productModel");
const Warehouse = require("../model/Warehouse/Warehouse");
const Inventory = require("../model/Inventory/Inventory");
const BulkPackage = require("../model/Inventory/BulkPackage");
const UnitSerial = require("../model/Barcode/UnitSerial");
const lotService = require("../services/lotService");
const barcodeService = require("../services/barcodeService");

let companyId, warehouseId, productId;

beforeEach(async () => {
  const c = await Company.create({
    fullName: "Co", email: `spl-${new mongoose.Types.ObjectId()}@x.com`, password: "x",
    companyInfo: { companyName: "Bhoomi AgriTech" },
  });
  companyId = c._id;
  warehouseId = (await Warehouse.create({ companyId, name: "Bhopal", code: "BHO" }))._id;
  productId = (await Product.create({ companyId, productName: "abc" }))._id;
});

/** Exactly what the Create Lot endpoint posts (lotController sets mintUnitLabels). */
const createLot = (extra = {}) =>
  lotService.receiveLot({
    ownerId: companyId, productId, warehouseId, qty: 10,
    lotOrigin: "company", pendingReceipt: true, mintUnitLabels: true,
    ...extra,
  });

const unitsOf = (inv) =>
  UnitSerial.find({ inventoryId: inv._id }).sort({ unit_serial: 1 }).lean();

describe("a SINGLE-PACKAGE lot is labelled at creation", () => {
  test("every unit of the lot gets a code — 10 qty, 10 codes", async () => {
    const inv = await createLot({ qty: 10 });

    const units = await unitsOf(inv);
    expect(units).toHaveLength(10);
    // Nothing was boxed, so nothing points at a box.
    expect(await BulkPackage.countDocuments({ lot_id: inv._id })).toBe(0);
    expect(units.every((u) => !u.bulk_packaging_record_id)).toBe(true);
  });

  test("the Labels page reads 10 of 10 rather than 0 of 10", async () => {
    const inv = await createLot({ qty: 10 });

    const counts = await barcodeService.unitCountsByLot({ ownerType: "company", ownerId: companyId });
    expect(counts[String(inv._id)]).toBe(10);
    expect(inv.originalQuantity).toBe(10);
  });

  test("THE FORMAT IS UNCHANGED — the same codes the manual button mints", async () => {
    // Two lots of the same SHAPE — both Khetify-numbered, both single package.
    // One is labelled automatically at creation…
    const auto = await createLot({ qty: 4 });
    // …the other is left to the on-demand flow and generated by hand.
    const manual = await lotService.receiveLot({
      ownerId: companyId, productId, warehouseId, qty: 4,
      lotOrigin: "company", pendingReceipt: true,
    });
    expect(await unitsOf(manual)).toHaveLength(0);
    await barcodeService.generateUnits(companyId, manual._id, 4, {});

    // The two lots differ only in the serial that closes their numbers, so that
    // is blanked and everything else — the shape — must be identical.
    const shapeOf = (codes) => codes.map((c) => c.replace(/-\d+$/, "-<SERIAL>"));
    const autoCodes = (await unitsOf(auto)).map((u) => u.serial);
    const manualCodes = (await unitsOf(manual)).map((u) => u.serial);

    expect(shapeOf(autoCodes)).toEqual(shapeOf(manualCodes));
    // …and it really is the composed shape (the SKU range collapsed to this
    // unit's own member), not some fallback.
    expect(autoCodes[0]).toMatch(/^KH-BHO-[A-Z]{3}\d{3}-\d{4}-\d{2}-\d{2}-SKU01-\d{4}$/);
  });

  test("a segmented lot number carries into the unit codes", async () => {
    const inv = await createLot({
      qty: 3,
      lotSegments: [
        { key: "company", type: "value", value: "BHO" },
        { key: "product", type: "value", value: "PRO" },
        { key: "batch", type: "value", value: "BAT" },
        { key: "sku", type: "range", mode: "variable", prefix: "SKU", digits: 3 },
      ],
    });

    // The LOT NUMBER is the operator's format in full — no serial appended.
    expect(inv.lotNumber).toBe("BHO-PRO-BAT-SKU001~SKU003");
    // Its UNIT CODES close with the lot's own serial, which is what keeps them
    // apart from another lot built from the same parts (lotDuplicateMessages).
    const s = String(inv.lot_number_serial).padStart(4, "0");
    const units = await unitsOf(inv);
    expect(units.map((u) => u.serial)).toEqual([
      `BHO-PRO-BAT-SKU001-${s}`, `BHO-PRO-BAT-SKU002-${s}`, `BHO-PRO-BAT-SKU003-${s}`,
    ]);
  });

  test("codes are unique, and a second create does not duplicate them", async () => {
    const inv = await createLot({ qty: 5 });
    const first = (await unitsOf(inv)).map((u) => u.serial);
    expect(new Set(first).size).toBe(5);

    // The same lot identity again — a top-up receive, not a new lot.
    await createLot({ qty: 5, lotNumber: inv.lotNumber });

    const after = (await unitsOf(inv)).map((u) => u.serial);
    expect(new Set(after).size).toBe(after.length);
    expect(after.slice(0, 5)).toEqual(first);
  });
});

describe("the boxed flow is untouched", () => {
  test("a BOXED lot is still labelled at creation, into its boxes", async () => {
    const inv = await createLot({
      qty: 10, hasBulkPackaging: true, numberOfBoxes: 2, unitsPerBox: 5,
    });

    const units = await unitsOf(inv);
    expect(units).toHaveLength(10);
    // Every unit sits in a box, five to each.
    expect(units.every((u) => u.bulk_packaging_record_id)).toBe(true);
    const boxes = await BulkPackage.find({ lot_id: inv._id }).sort({ box_serial: 1 });
    for (const b of boxes) {
      expect(await UnitSerial.countDocuments({ bulk_packaging_record_id: b._id })).toBe(5);
    }
  });
});

describe("callers that never opted in keep the on-demand flow", () => {
  test("without mintUnitLabels nothing is minted — GRN, seeder, internal callers", async () => {
    const inv = await lotService.receiveLot({
      ownerId: companyId, productId, warehouseId, qty: 10,
      lotOrigin: "company", pendingReceipt: true,
    });

    expect(await unitsOf(inv)).toHaveLength(0);
    // …and the manual button still works for them.
    await barcodeService.generateUnits(companyId, inv._id, 10, {});
    expect(await unitsOf(inv)).toHaveLength(10);
  });
});

describe("a failed create leaves no codes behind", () => {
  test("a rejected lot mints nothing", async () => {
    await expect(lotService.receiveLot({
      ownerId: companyId, productId, warehouseId, qty: 10,
      lotOrigin: "company", mintUnitLabels: true,
      // boxes × units-per-box must equal the quantity — this is refused before
      // a lot number is minted or any stock is touched.
      hasBulkPackaging: true, numberOfBoxes: 3, unitsPerBox: 4,
    })).rejects.toMatchObject({ status: 400 });

    expect(await UnitSerial.countDocuments({ companyId })).toBe(0);
    expect(await Inventory.countDocuments({ ownerId: companyId })).toBe(0);
  });
});
