// FAQ content for the Company and Seller portals. Pure data (no JSX) so the same
// shared <FaqView /> can render either set, and the copy stays easy to edit in
// one place. Grouped by category; each item is { q, a }.

export const COMPANY_FAQ = [
  {
    category: 'Registration & Onboarding',
    icon: 'how_to_reg',
    items: [
      { q: 'How do I create a company account on Khetify?', a: 'Click the "Register as Company" button on the home page and complete the registration form by providing your company name, email address, phone number, and password. Once submitted, your company account will be created.' },
      { q: 'What documents are required to register a company?', a: 'During the onboarding process, you will be asked to provide your business name, GST number, trade license, contact information, and bank/PAN details for verification.' },
      { q: 'Is company registration free?', a: 'Yes, creating a company account is completely free. However, some advanced features are available only with a premium subscription plan. Please refer to the Billing section for more information.' },
      { q: 'How many company accounts can be created using one email address?', a: 'Only one company account can be registered with a single email address. If you need to register another company, you must use a different email address.' },
      { q: 'What happens after I complete the registration?', a: 'Your application will be submitted for review. Once it is approved, you will receive access to the Company Dashboard and all available company features.' },
      { q: 'How long does the approval process take?', a: 'In most cases, the approval process is completed within 24 hours. However, additional verification may require extra processing time.' },
      { q: 'Why was my registration application rejected?', a: 'Your application may be rejected due to incomplete or incorrect information, an invalid GST number, duplicate company registration, or missing verification documents. Please contact the support team for the exact reason and further assistance.' },
      { q: 'What are the steps involved in the registration process?', a: 'The registration process consists of: 1) Enter basic company information. 2) Complete the company setup (Steps 2–5). 3) Upload the required documents. 4) Submit your application. 5) Wait for approval. Your progress is automatically saved at each step.' },
      { q: 'Will my information be saved if I leave the setup before completing it?', a: 'Yes. Your progress is automatically saved, allowing you to resume the registration process from where you left off.' },
      { q: 'Can I edit my registration details after submitting the application?', a: 'Some information can be updated before your application is approved. Once approved, changes to certain details may require submitting a support request.' },
      { q: 'Does Khetify handle logistics and payments?', a: 'No. Khetify provides the platform infrastructure, product visibility, and business network. Delivery, logistics, and payment transactions are managed directly between the company and the seller.' },
      { q: 'Who should I contact if I need help during onboarding?', a: 'If you need assistance during the onboarding process, please contact our support team at support@khetify.com. Our team typically responds within 24 hours and will help you complete your storefront setup.' },
    ],
  },
  {
    category: 'Company Setup & Approval',
    icon: 'business',
    items: [
      { q: 'What information should be configured in the company profile?', a: 'Your company profile should include company information, logo, registered address, GST/license details, warehouse information, and bank details.' },
      { q: 'What should I do after seeing the "Submission Complete" message?', a: 'Once your application has been submitted successfully, simply wait for the approval process to be completed. After approval, you will receive a confirmation notification and your Company Dashboard will be activated.' },
      { q: 'How can I check my application approval status?', a: 'Log in to your company account to view your application status. The status will be displayed as Pending, Approved, or Rejected.' },
      { q: 'Can I update my company details after approval?', a: 'Yes. General company information can be updated from the Company Settings page. However, changes to legal information such as the company name or GST details require assistance from the support team.' },
      { q: 'Can I update my company setup later?', a: 'Yes. Most company information can be updated at any time from the Company Information or Settings page.' },
      { q: 'Can I add multiple branches or warehouse locations?', a: 'Yes. Khetify allows you to add and manage multiple warehouses or branch locations through the Warehouses section.' },
      { q: 'How do I update my company logo and branding?', a: 'You can upload a new company logo and update your branding information from the Company Profile or Settings page.' },
      { q: 'What should I do if I entered incorrect information during the setup process?', a: 'If your application has not yet been approved, you can return to the relevant step and update the information. After approval, you will need to submit a support request under the Account & Settings category to request any necessary changes.' },
    ],
  },
  {
    category: 'Account, Login & Security',
    icon: 'lock',
    items: [
      { q: 'How do I log in to my company account?', a: 'Go to the Company Login page and sign in using your registered email address and password.' },
      { q: 'What should I do if I forget my password?', a: 'Click "Forgot Password", enter your registered email address, and follow the password reset link sent to your inbox to create a new password.' },
      { q: 'How long is the password reset link valid?', a: 'For security reasons, the password reset link is valid only for a limited period. If the link expires, you will need to request a new one.' },
      { q: 'How can I change my password?', a: 'After logging in, navigate to Settings and update your password from the Account Security section.' },
      { q: 'How is my company account secured?', a: 'Your account is protected using enterprise-grade encryption, secure authentication, and role-based access control to help safeguard your data.' },
      { q: 'Can multiple users access the same company account?', a: 'Yes. You can add multiple team members from the Users/Team section and assign appropriate roles and permissions based on their responsibilities.' },
      { q: 'I am unable to log in. What should I do?', a: 'First, verify that you are using the correct email address and password. If the issue persists, try resetting your password. If you still cannot access your account, please submit a support request for assistance.' },
      { q: 'Why has my account been temporarily locked?', a: 'Your account may be temporarily locked due to multiple unsuccessful login attempts or security-related reasons. Please contact the support team to have your account unlocked.' },
    ],
  },
  {
    category: 'Dashboard & Navigation',
    icon: 'dashboard',
    items: [
      { q: 'What information is available on the dashboard?', a: 'The dashboard provides a real-time overview of your sales, orders, inventory levels, returns, payments, and other key business metrics.' },
      { q: 'Where can I find notifications?', a: 'You can view notifications in the Notifications section, where you will receive updates about orders, approvals, inventory alerts, and important system announcements.' },
      { q: 'What are the main modules available in the Company Portal?', a: 'The Company Portal includes: Inventory Management System (IMS), Product Catalog, Orders, Returns, Sellers, Supply Requests, Billing, Users, and Support.' },
      { q: 'How frequently is the dashboard updated?', a: 'The dashboard is updated in real time, ensuring that changes to inventory, orders, and payments are reflected immediately.' },
      { q: 'Can I access the Company Portal on a mobile device?', a: 'Yes. The Company Portal is fully responsive and can be accessed from both desktop and mobile devices.' },
    ],
  },
  {
    category: 'Product Upload & Catalog',
    icon: 'inventory_2',
    items: [
      { q: 'How do I upload a product?', a: 'Go to the Upload Product page and enter the product name, category, pricing, images, and inventory details. Once all required information is provided, submit the product to add it to your catalog.' },
      { q: 'Can I upload multiple products in bulk?', a: 'Yes. Khetify supports bulk product uploads, allowing you to upload and manage your entire inventory efficiently using the bulk import feature.' },
      { q: 'How can I edit an existing product?', a: 'Navigate to the Product Catalog, select the product you want to modify, and click Edit Product to update its details.' },
      { q: 'What image formats are supported for product uploads?', a: 'Khetify supports standard image formats such as JPG and PNG. For the best customer experience, use high-quality, clear product images.' },
      { q: 'How do I delete or deactivate a product?', a: 'Open the product from the Product Catalog and use the available options to either deactivate or permanently remove it from your catalog.' },
      { q: 'Can I update the product price later?', a: 'Yes. Product pricing can be updated at any time through the Edit Product page.' },
      { q: 'What product categories are available?', a: 'Khetify supports a wide range of agricultural product categories, including seeds, fertilizers, irrigation equipment, farming tools, crop protection products, and more. Select the category that best matches your product.' },
      { q: 'My bulk product upload failed. What should I do?', a: 'Verify that your upload file follows the required format and contains the correct column structure. If the issue persists, submit a support request under the Product Upload category.' },
      { q: 'Are products reviewed before they are published?', a: "Yes. In certain cases, products may undergo a review process to ensure they comply with Khetify's product listing guidelines before becoming publicly available." },
      { q: 'Can I add multiple variants for a single product?', a: 'Yes. You can create multiple product variants based on attributes such as size, quantity, packaging type, or other applicable options.' },
      { q: 'Where can I find the product upload guidelines?', a: 'Detailed product upload guidelines are available in the Support Center under the Product Upload Guidelines section.' },
      { q: 'Will out-of-stock products still appear in the catalog?', a: "When a product's inventory reaches zero, it is automatically marked as Out of Stock. You can choose to hide the product or restock it to make it available again." },
    ],
  },
  {
    category: 'Inventory Management (IMS)',
    icon: 'warehouse',
    items: [
      { q: 'What is IMS?', a: "IMS (Intelligent Inventory Management System) is Khetify's inventory management solution that provides real-time stock tracking across multiple warehouses, automated reorder management, and batch and expiry tracking." },
      { q: 'How are inventory levels calculated?', a: 'Available Stock = Online Stock + Offline Stock − Reserved Stock. Every inventory transaction is recorded in a secure audit ledger for complete traceability.' },
      { q: 'Can inventory be synchronized across multiple warehouses?', a: 'Yes. Khetify automatically synchronizes inventory across all connected warehouses, providing a unified view of stock availability.' },
      { q: 'Does Khetify support batch and expiry management?', a: 'Yes. Products can be managed using batch numbers and expiry dates, enabling accurate inventory tracking and compliance.' },
      { q: 'Will I receive alerts before products expire?', a: 'Yes. Khetify sends automated notifications before products reach their expiry date, helping you minimize waste and manage inventory more effectively.' },
      { q: 'How does automatic reordering work?', a: 'When inventory falls below the predefined minimum stock level, the system can automatically trigger a reorder based on your inventory settings.' },
      { q: 'How can I adjust inventory manually?', a: 'You can manually increase or decrease inventory through the IMS module. Every adjustment is recorded in the audit log to maintain complete inventory history.' },
      { q: 'What are lots?', a: 'A lot represents a specific production batch or consignment of products. Lots enable complete tracking and traceability throughout the product lifecycle.' },
      { q: 'How do I record inbound inventory (GRN)?', a: 'Receive incoming goods through the Inbound section and create a Goods Receipt Note (GRN). Once the GRN is posted, inventory levels are updated automatically.' },
      { q: 'How is outbound inventory managed?', a: 'Use the Outbound section to record product dispatches. The system automatically reserves and deducts inventory based on the dispatched quantities.' },
      { q: 'Can I view my inventory movement history?', a: 'Yes. Khetify maintains an append-only inventory ledger that records every stock movement. These records provide a complete audit trail and cannot be deleted.' },
      { q: 'What should I do if my inventory appears incorrect?', a: 'Review your inventory movement ledger to identify any discrepancies. If the issue cannot be resolved, submit a support request under the Inventory & Stock category for further assistance.' },
    ],
  },
  {
    category: 'Warehouses & Operations',
    icon: 'local_shipping',
    items: [
      { q: 'How do I add a new warehouse?', a: 'Navigate to the Warehouses section and enter the warehouse name, location, and storage capacity. Once the required information is provided, save the details to add the warehouse.' },
      { q: 'Can I transfer inventory between warehouses?', a: 'Yes. Khetify supports secure inter-warehouse inventory transfers. Every transfer is recorded automatically to maintain an accurate inventory history.' },
      { q: 'Can I view warehouse-specific inventory reports?', a: 'Yes. You can access detailed inventory and stock movement reports for each warehouse individually.' },
      { q: 'What can I manage in the Operations section?', a: 'The Operations module allows you to manage inbound shipments, outbound dispatches, warehouse transfers, and other day-to-day warehouse activities.' },
      { q: 'Can I monitor warehouse capacity?', a: 'Yes. Khetify enables you to track both the total warehouse capacity and current occupancy to help optimize storage utilization.' },
      { q: 'Can I generate labels and barcodes?', a: 'Yes. Product labels and lot barcodes can be generated from the Labels section for inventory identification and traceability.' },
    ],
  },
  {
    category: 'Orders',
    icon: 'receipt_long',
    items: [
      { q: 'Where can I view my orders?', a: 'All incoming orders can be viewed on the Company Orders page, along with their current processing status.' },
      { q: 'What order statuses are available?', a: 'Orders can have the following statuses: New, Processing, Dispatched, Delivered, and Cancelled.' },
      { q: 'How do I process an order?', a: 'Open the order, review the details, accept it, and update the packing and dispatch information. The inventory is automatically adjusted based on the order.' },
      { q: 'Where can I view my order history?', a: 'You can access previous orders from the Order History page, where orders can be searched, filtered, and reviewed.' },
      { q: 'Are invoices generated automatically?', a: 'Yes. Khetify automatically generates GST-compliant invoices for eligible orders.' },
      { q: 'What happens to inventory if an order is cancelled?', a: 'When an order is cancelled, the reserved inventory is automatically released and added back to the available stock.' },
      { q: 'Does Khetify handle product delivery?', a: 'No. Khetify provides the platform for order management and visibility. Delivery and logistics are managed directly by the company or its logistics partner.' },
      { q: 'How are payments collected?', a: 'Payments are settled directly between the company and the seller. Khetify does not process or manage payment transactions.' },
    ],
  },
  {
    category: 'Returns',
    icon: 'assignment_return',
    items: [
      { q: 'How are product returns managed?', a: 'Return requests are available on the Company Returns page, where you can review each request and either approve or reject it based on your return policy.' },
      { q: 'Is inventory updated after a return is approved?', a: 'Yes. Once a return request is approved, the returned items are automatically added back to your available inventory.' },
      { q: 'Is there a time limit for product returns?', a: "Yes. The return window is determined by your company's return policy and the agreed terms with the seller." },
      { q: 'Can I reject a return request?', a: 'Yes. You may reject a return request if it does not comply with your return policy. It is recommended to provide a reason for the rejection.' },
      { q: 'Where can I find the return and issue handling guidelines?', a: 'Detailed return policies and issue handling procedures are available in the Support Center under the Returns & Issue Handling section.' },
    ],
  },
  {
    category: 'Sellers / Dealers (CRM)',
    icon: 'groups',
    items: [
      { q: 'How do I add sellers or dealers?', a: 'Go to the Company Sellers section to create a new dealer profile or invite sellers to join your business network.' },
      { q: 'How can I manage seller applications?', a: 'Seller applications can be reviewed from the Supply Requests or PC Applications section, where you can approve or reject each request.' },
      { q: 'Can I set a credit limit for dealers?', a: 'Yes. You can configure individual credit limits for each dealer based on your business requirements.' },
      { q: 'Can I monitor dealer performance?', a: 'Yes. Each dealer profile includes performance metrics, order history, and other relevant information to help you evaluate their performance.' },
      { q: 'Can I block or deactivate a seller?', a: 'Yes. Sellers who fail to comply with your business policies can be blocked or deactivated from the Sellers section.' },
      { q: 'Can I view all orders placed by a dealer?', a: 'Yes. Each dealer profile contains a complete order history, making it easy to review previous transactions.' },
      { q: 'How can I connect with new sellers?', a: 'Khetify provides access to a pre-verified network of sellers, helping you discover and connect with reliable business partners.' },
      { q: 'How are seller ratings determined?', a: 'Seller ratings are calculated based on factors such as order fulfillment performance, delivery timeliness, and overall transaction history.' },
    ],
  },
  {
    category: 'Supply Requests & Transport',
    icon: 'sync_alt',
    items: [
      { q: 'What is a supply request?', a: 'A supply request is a request submitted by a seller for product inventory. Companies can review and fulfill these requests based on product availability.' },
      { q: 'How do I approve a supply request?', a: 'Navigate to the Supply Requests section, open the request, review its details, and choose to Accept or Decline it.' },
      { q: 'How can I track shipments?', a: 'Shipments can be created, monitored, and tracked through the IMS Transport module, providing real-time shipment visibility.' },
      { q: 'How is shipment verification performed?', a: 'Shipments are verified during both dispatch and receipt. Every verification event is automatically recorded in the audit log to ensure complete traceability.' },
    ],
  },
  {
    category: 'Traceability & Lots',
    icon: 'track_changes',
    items: [
      { q: 'What is product traceability?', a: 'The Trace feature enables you to track a product lot throughout its entire lifecycle, from production to final delivery, ensuring complete end-to-end traceability.' },
      { q: 'How can I trace a specific batch or lot?', a: 'Go to the Trace/Lots section, enter the Lot ID, and view the complete lifecycle of the batch, including its movement, storage locations, and transaction history.' },
      { q: 'How do I perform a product recall?', a: 'Using the traceability system, you can quickly identify affected lots and initiate a product recall. All recall activities are securely recorded in the audit log for compliance purposes.' },
      { q: 'What information is available in the Lot Dashboard?', a: "The Lot Dashboard provides a centralized view of each lot's inventory, movement history, warehouse location, and current status." },
    ],
  },
  {
    category: 'Billing & Subscription',
    icon: 'payments',
    items: [
      { q: 'Where can I find my billing information?', a: 'You can view your current subscription plan, invoices, payment history, and billing status from the Billing section of the Company Portal.' },
      { q: 'What subscription plans are available?', a: 'Khetify offers Basic and Premium subscription plans. Premium plans provide access to additional features and advanced functionality.' },
      { q: 'How can I upgrade or downgrade my subscription plan?', a: 'You can change your subscription plan at any time from the Billing section by selecting the desired plan.' },
      { q: 'Why is a premium feature locked?', a: 'The feature is not included in your current subscription plan. Upgrade to a Premium plan to gain access to premium features.' },
      { q: 'What should I do if my payment fails?', a: 'Verify your payment method and try the transaction again. If the problem persists, submit a support request under the Billing & Subscription category.' },
      { q: 'Can I download my invoices?', a: 'Yes. All generated invoices are available for download from the Billing section.' },
    ],
  },
  {
    category: 'Users, Roles, Compliance & Support',
    icon: 'manage_accounts',
    items: [
      { q: 'How do I assign roles to team members?', a: 'Navigate to the Users section, add a new team member, and assign an appropriate role such as Administrator, Staff, or Read-Only Auditor based on their responsibilities.' },
      { q: 'How can I get help if I encounter an issue?', a: 'If you need assistance, visit the Support Center and create a support request by selecting the appropriate category. Our support team typically responds within 4 business hours. Support Email: support@khetify.com. Support Hours: Monday to Saturday, 9:00 AM – 6:00 PM.' },
    ],
  },
];

export const SELLER_FAQ = [
  {
    category: 'Registration & Onboarding',
    icon: 'how_to_reg',
    items: [
      { q: 'How do I register as a seller on Khetify?', a: 'Click the \"Register as Seller\" button on the seller page and complete the registration form by providing your name, email address, phone number, and password. Your seller account will then be created.' },
      { q: 'What information is required to register as a seller?', a: 'During the onboarding steps, you will be asked to provide your shop or business name, contact details, address, GST or license details (if applicable), and bank/PAN details.' },
      { q: 'Is seller registration free?', a: 'Yes, creating a seller account is free. However, some advanced features depend on your subscription plan or authorization status.' },
      { q: 'What should I do after completing the registration?', a: 'Complete the onboarding process, fill in your profile, and then apply for a Principal Certificate (PC) from each company whose products you wish to sell.' },
      { q: 'Will my information be saved if I leave the onboarding before completing it?', a: 'Yes. Your progress is saved automatically, allowing you to resume from where you left off.' },
      { q: 'Is my account activated immediately?', a: 'Your account is created immediately. However, to sell any company products, that company must first issue you a Principal Certificate (PC).' },
    ],
  },
  {
    category: 'Login, Account & Security',
    icon: 'lock',
    items: [
      { q: 'How do I log in to my seller account?', a: 'Go to the Seller Login page and sign in using your registered email address and password.' },
      { q: 'What should I do if I forget my password?', a: 'Click \"Forgot Password\", request a reset link on your registered email address, and follow it to set a new password.' },
      { q: 'How can I change my password?', a: 'After logging in, navigate to Settings or Profile and update your password from there.' },
      { q: 'Is my data secure?', a: 'Yes. Your account and data are protected using encryption and role-based access control.' },
      { q: 'I am unable to log in. What should I do?', a: 'First, verify that you are using the correct email address and password, then try resetting your password. If the issue persists, please contact the support team.' },
      { q: 'Can multiple users access the same seller account?', a: 'Yes. You can add team members with assigned roles from the Team section.' },
    ],
  },
  {
    category: 'Companies & Principal Certificate (PC)',
    icon: 'verified',
    items: [
      { q: 'What is a Principal Certificate (PC)?', a: 'A Principal Certificate is the authorization a company grants you so that you can officially sell its products.' },
      { q: 'How do I apply for a PC?', a: 'Search for the company in the Companies section, click \"Apply for PC\", and complete the application form.' },
      { q: 'How do I find a company?', a: 'Enter the company name or region in the search box on the Companies page.' },
      { q: 'What are recommended companies?', a: 'These are companies suggested to you based on your profile and region, for which you can apply for a Principal Certificate.' },
      { q: 'How can I check the status of my PC application?', a: 'The status is displayed on the Companies or Certifications page as In progress, PC issued (active), or Rejected.' },
      { q: 'What does \"PC issued\" mean?', a: 'It means the company has authorized you, and you can now sell its products.' },
      { q: 'Why was my PC application rejected?', a: 'An application may be rejected due to incomplete details, eligibility criteria, or the company policy. You may apply again.' },
      { q: 'How many companies can I hold a PC for at the same time?', a: 'You can apply for and hold a Principal Certificate from multiple companies at the same time.' },
      { q: 'Can I sell a company products without a PC?', a: 'No. A Principal Certificate from that company is required before you can sell any of its products.' },
      { q: 'What is available on the Certifications page?', a: 'This page is where you manage your PC applications and company-specific certification forms.' },
    ],
  },
  {
    category: 'Dashboard & Hub',
    icon: 'dashboard',
    items: [
      { q: 'What information is available on the seller dashboard?', a: 'The dashboard provides an overview of your sales, orders, inventory, active companies (PC), and overall performance.' },
      { q: 'What is included in the Administration section?', a: 'The Administration section contains account-level areas such as Team, Certifications, Billing, Customers, and Companies.' },
      { q: 'How frequently is the data updated?', a: 'The data is updated in real time, so changes to orders and stock are reflected immediately.' },
      { q: 'Can I access the seller portal on a mobile device?', a: 'Yes. The portal is fully responsive and works on both mobile and desktop devices.' },
    ],
  },
  {
    category: 'Product Catalog & Inventory',
    icon: 'inventory_2',
    items: [
      { q: 'What is included in the seller product catalog?', a: 'The catalog contains the products of every company for which you hold a Principal Certificate, and you can manage and sell them from there.' },
      { q: 'Are products added automatically?', a: 'The authorized products of a company become available to you automatically, and you manage them along with your own stock.' },
      { q: 'What are marketplace listings?', a: 'These are the products you have published on your Khetify storefront.' },
      { q: 'How is seller inventory managed?', a: 'The Inventory section tracks the stock, batch, and availability of each of your products.' },
      { q: 'How is available stock calculated?', a: 'Available stock = online + offline − reserved. It is adjusted automatically whenever a sale or reservation takes place.' },
      { q: 'Are batch and expiry details tracked?', a: 'Yes. You can control your stock with batch numbers and expiry dates.' },
      { q: 'Will I receive low-stock alerts?', a: 'Yes. You will receive an alert whenever stock falls below the minimum level.' },
      { q: 'Can I view the stock movement history?', a: 'Yes. An append-only ledger is maintained for every stock change.' },
    ],
  },
  {
    category: 'Warehouses & Operations',
    icon: 'local_shipping',
    items: [
      { q: 'How do I add a warehouse?', a: 'Go to the Warehouses section and add a warehouse by providing its name, location, and capacity.' },
      { q: 'Can I maintain multiple warehouses?', a: 'Yes. You can add more than one storage location.' },
      { q: 'Can stock be transferred between warehouses?', a: 'Yes. Inter-warehouse transfers are supported and are recorded safely.' },
      { q: 'What is included in the Operations section?', a: 'The Operations section covers day-to-day stock activities such as inbound, outbound, transfers, and traceability.' },
      { q: 'Can labels and barcodes be printed?', a: 'Yes. You can generate and print product and lot barcodes from the Labels section.' },
    ],
  },
  {
    category: 'Outbound, Supply & Customers',
    icon: 'local_mall',
    items: [
      { q: 'What is Outbound?', a: 'The Outbound section is where you dispatch and sell products to your customers and dealers.' },
      { q: 'Is stock returned if an order is cancelled?', a: 'Yes. Reserved stock is released automatically when an order is cancelled.' },
      { q: 'Does Khetify handle delivery?', a: 'No. You arrange delivery yourself. The platform only provides order visibility.' },
      { q: 'What is a supply request?', a: 'When you need stock from a company, you send a replenishment request from the Supply section.' },
      { q: 'How can I check the status of a supply request?', a: 'The Supply page displays each request along with its status: pending, approved, or fulfilled.' },
      { q: 'What is included in the Customers section?', a: 'The Customers section holds the details, order history, and relationship management for your buyers, farmers, and dealers.' },
      { q: 'Is customer credit and outstanding balance tracked?', a: 'Yes. You can manage customer-wise dues and credit details.' },
    ],
  },
  {
    category: 'Team, Analytics, Billing & Support',
    icon: 'payments',
    items: [
      { q: 'How do I add team members?', a: 'Add a member from the Team section and assign the appropriate role (admin, manager, or staff).' },
      { q: 'Is role-based access available?', a: 'Yes. Different members can be given different permissions, such as read-only access for staff or auditors.' },
      { q: 'What is available in Analytics?', a: 'Analytics provides sales trends, top products, stock aging, expiry, and movement reports.' },
      { q: 'What is included in Billing?', a: 'Billing shows your subscription plan and usage. Switching plans is restricted to administrators.' },
      { q: 'What is Khetify responsible for?', a: 'Khetify provides the platform infrastructure, pricing visibility, and network access. Delivery and payments are managed by you.' },
      { q: 'How can I get help if I face an issue?', a: 'Raise a request from the Support or Help option in the portal, or contact the support team. Please describe your issue in detail so that it can be resolved quickly.' },
    ],
  },
];