import React, { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import Swal from 'sweetalert2';
import {
  getLots, getUnits, getUnitCounts, generateUnits, markUnitsPrinted, recallLot, getBulkPackages,
} from '../../../lib/imsApi';
import { Field, inputCls, PrimaryBtn, GhostBtn, Modal } from './ImsUi';
import Barcode128 from '../../../lib/barcode128';
import LotLabel from '../../../Components/ims/LotLabel';
import BulkPackageLabel from '../../../Components/ims/BulkPackageLabel';
import { usePermission } from '../../../context/PermissionContext';
import { isWarehouseRole } from '../../../lib/roles';

// Child unit serials are minted and controlled by the MAIN COMPANY. A Company
// Warehouse works the labels it has received — view, print, reprint — but never
// creates new unit records, so the generate controls are shown in a disabled
// state (not removed: the lot quantity and generated-unit count are exactly what
// the warehouse needs to read). The button being disabled is UX only; the real
// enforcement is barcodeService.generateUnits' role guard.
const GENERATE_LOCKED_MSG = 'Units can only be generated by the Main Company.';
// Every physical unit of the lot already carries a label. Printing and
// reprinting stay available; only minting new records is finished.
const ALL_LABELLED_MSG = 'All unit labels for this lot have already been generated.';

const toast = (icon, title) =>
  Swal.fire({ icon, title, toast: true, position: 'top-end', timer: 2200, showConfirmButton: false });
const apiError = (err) => toast('error', err?.response?.data?.message || err.message || 'Something went wrong');
const listOf = (r) => (Array.isArray(r) ? r : r?.data || []);

// label layouts: id -> { cols, w(mm), h(mm), label }
const LAYOUTS = {
  '65': { cols: 5, w: 38, h: 21, label: '65 / page · 38×21mm' },
  '24': { cols: 3, w: 64, h: 34, label: '24 / page · 64×34mm' },
};

const PRINT_CSS = `
/* The MASTER lot label — rendered ONCE for the whole sheet, above and outside
   the per-box page cards. It is the lot's common identity; the box cards below
   carry only what differs between boxes. */
.lot-master { margin: 0 auto 1.5rem; }

/* On screen the box pages sit SIDE BY SIDE in a responsive grid, so a 4-box lot
   reads as 4 cards rather than a long vertical scroll. In print the grid
   collapses to a block flow and each card takes its own sheet (below). */
.bp-grid { display: grid; gap: 1.25rem; align-items: start; justify-content: center; }

/* A page card: one printable page. Bordered on screen so page boundaries are
   obvious; bare in print. */
.print-page {
  margin: 0 auto;
  border: 1px dashed #d6d3d1;
  border-radius: 0.75rem;
  padding: 1rem;
  background: #fff;
}
/* Every label block is centred and never split across a page boundary. */
.print-page .label-block, .lot-master { break-inside: avoid; page-break-inside: avoid; }
.print-page .label-block { margin-left: auto; margin-right: auto; }

/* Unit labels: a centred wrap, so a partial last row sits in the middle
   (3 on top, 2 centred beneath) instead of hugging the left edge. The container
   is capped to an exact number of labels, which is what stops a row from
   stretching into one long line. */
.unit-grid { display: flex; flex-wrap: wrap; justify-content: center; gap: 2mm; margin: 0 auto; }
.unit-grid > * { break-inside: avoid; page-break-inside: avoid; }

/* THREE-LEVEL PACKAGING. A main box card holds its own inner box cards inside
   its border, so the nesting on screen is the nesting in the warehouse. */
.main-card { border: 1px solid #e7e5e4; border-radius: 1rem; padding: 1rem; background: #fff; }
.inner-stack { display: grid; gap: 1rem; margin-top: 1rem; }
.inner-card { border: 1px dashed #d6d3d1; border-radius: 0.75rem; padding: 0.75rem; background: #fafaf9; }

/* A LONE CARD ON THE LAST ROW IS CENTRED. With an odd number of inner boxes the
   final card would otherwise sit in column 1 with a gap beside it. It spans both
   columns and is centred at the width of a normal card, so it stays the same
   size as its siblings — rows of two are untouched. */
.inner-stack > .inner-card:last-child:nth-child(odd) {
  grid-column: 1 / -1;
  justify-self: center;
  width: calc(50% - 0.5rem); /* half the row minus half the 1rem grid gap */
}

@media print {
  body * { visibility: hidden; }
  #label-sheet, #label-sheet * { visibility: visible; }
  #label-sheet { position: absolute; left: 0; top: 0; width: 100%; }
  .no-print { display: none !important; }
  @page { size: A4; margin: 10mm; }

  /* Screen-only chrome off; cards flow one per page instead of side by side. */
  .print-page { border: 0; padding: 0; margin: 0 auto; max-width: none; }
  .bp-grid { display: block; }

  /* The nesting is screen structure. On paper every box is its own sheet, in
     document order: lot → main box → its inner boxes and their units → next
     main box. So the containers lose their borders and stop indenting. */
  .main-card { border: 0; padding: 0; margin: 0; }
  .inner-stack { display: block; margin: 0; }
  .inner-card { border: 0; padding: 0; margin: 0; background: none; }
  /* Each box is its own full-width sheet in print, so the screen-only centring
     of a lone last card must not narrow it. */
  .inner-stack > .inner-card:last-child:nth-child(odd) { grid-column: auto; width: auto; }

  /* The master lot label takes the first sheet; every box card then gets its
     own. :last-child drops the trailing break so the run never ends on a blank
     page. (Only applied when box cards follow — see .lot-master.has-pages.) */
  .lot-master.has-pages { page-break-after: always; break-after: page; }
  .bp-page { page-break-after: always; break-after: page; }
  .bp-page:last-child { page-break-after: auto; break-after: auto; }

  /* NESTED (three-level) sheets break BEFORE each box instead of after it. A
     break-after rule cannot work here: the last inner box of main box 1 is a
     :last-child too, so it would lose the break that separates it from main box
     2 — and the last box of the whole run would still leave a blank sheet.
     Breaking before every box gets both right, and leaves the lot label alone
     on the first sheet without needing .has-pages. */
  .nested-sheet .bp-page {
    page-break-before: always; break-before: page;
    page-break-after: auto; break-after: auto;
  }
}`;

/**
 * How many unit labels this lot can EVER have — the lot's ORIGINAL CREATED
 * quantity (Inventory.originalQuantity, immutable, written once at creation).
 *
 * Deliberately NOT live stock. A unit label is a sticker for a unit that was
 * manufactured into the lot, so the count is fixed when the lot is created and
 * has nothing to do with what a warehouse currently holds, has received, has
 * dispatched or has transferred away. Reading availableStock is what produced
 * the "avail 0" the dropdown used to show for a lot the warehouse hadn't
 * confirmed yet.
 *
 * For a Bulk Packaging lot this is also exactly boxes × units-per-box, since
 * lotService enforces that identity at creation.
 *
 * Legacy rows that predate originalQuantity (the 005-original-lot-quantity
 * migration could not prove a value) fall back to on-hand + in-transit — the
 * closest thing those rows have. Mirrors barcodeService.generateUnits' cap.
 */
const lotOriginalQty = (l) =>
  typeof l?.originalQuantity === 'number'
    ? l.originalQuantity
    : Number(l?.availableStock || 0) + Number(l?.inTransitStock || 0);

// Unit labels per row inside a Bulk Packaging page card. Capped at 3 so a
// 5-unit box reads as a balanced 3 + 2 instead of one stretched line.
// NOTE: this cap is independent of the card width — a wider card must NOT fit
// 4 or 5 labels per row.
const BOX_UNIT_COLS = 3;
const GAP_MM = 2;

// Width of the two TOP-LEVEL cards — the master lot label and the main Bulk
// Packaging Box label under it — so they read as one centred column.
// 600px is LotLabel's own fixed width (w-[600px]); the wrapper used to cap at
// max-w-sm (384px), which is narrower than the label it holds, so the label
// overflowed its box to the right and looked off-centre.
// Deliberately NOT applied to the inner box cards or the unit grids: those are
// sized from the label preset (rowWidthMm) and stay as they are.
const TOP_CARD_W = 600;

/** Width of a row of `cols` labels of `w` mm, gaps included. */
const rowWidthMm = (cols, w) => cols * w + (cols - 1) * GAP_MM;

/**
 * The unit-label grid. A centred wrap rather than a rigid CSS grid, so a
 * partial last row sits in the middle of the page (3 on top, 2 centred beneath)
 * instead of hugging the left edge.
 *
 * `cols` caps how many sit next to each other: 3 inside a Bulk Packaging page
 * card (so 5 units read as a balanced 3 + 2), and the selected preset's own
 * column count for a plain lot — which may hold thousands of units, where
 * forcing 3 per row would waste most of the sheet. The label SIZE always comes
 * from the preset either way.
 */
export const UnitGrid = ({ units, lot, cfg, bcH, boxed = false, cols }) => {
  const perRow = Math.max(1, cols || cfg.cols);
  return (
    <div className="unit-grid" style={{ maxWidth: `${rowWidthMm(perRow, cfg.w)}mm` }}>
      {units.map((u) => (
        <div
          key={u.serial}
          style={{ width: `${cfg.w}mm`, height: `${cfg.h}mm` }}
          className="border border-stone-300 rounded-sm p-1 flex flex-col items-center justify-center overflow-hidden"
        >
          <p className="text-[7px] font-bold text-stone-800 leading-tight text-center truncate w-full">
            {lot?.productId?.productName || 'Item'}
          </p>
          {/* Boxed lots identify the unit by its box + in-box number; plain lots
              keep the lot number they have always shown. */}
          <p className="text-[6px] text-stone-500 leading-tight truncate w-full text-center">
            {boxed ? `Box ${u.box_serial} · Unit ${String(u.unit_serial ?? '').padStart(3, '0')}` : u.lotNumber}
          </p>
          <Barcode128 value={u.serial} height={bcH} width={1} className="w-full" />
          <p className="text-[6px] font-mono text-stone-700 leading-tight break-all text-center">{u.serial}</p>
        </div>
      ))}
    </div>
  );
};

const ImsLabels = () => {
  const canRecall = usePermission('recall:execute');
  const { role } = usePermission();
  // operations_manager | warehouse_manager | warehouse_operator | inventory_manager
  const isWarehouse = isWarehouseRole(role);
  const [searchParams] = useSearchParams();
  const [lots, setLots] = useState([]);
  const [lotId, setLotId] = useState('');
  const [units, setUnits] = useState([]);
  // The selected lot's PHYSICAL OUTER BOXES. Empty for a single-package lot,
  // which is what keeps that lot on the original flat-grid layout.
  const [boxes, setBoxes] = useState([]);
  // The MAIN (outer) bulk packaging boxes, when the lot has three levels. Empty
  // for a two-level lot and for every lot created before the level existed —
  // which is what keeps those on the flat one-card-per-box layout.
  const [mainBoxes, setMainBoxes] = useState([]);
  // The lot's own box total, so "Box 2 of 4" reads the same at the warehouse
  // that received two of them as it does on the printed carton.
  const [totalBoxes, setTotalBoxes] = useState(null);
  // Unit-label count for EVERY lot, keyed by inventoryId. One aggregate call —
  // the dropdown needs a real number for each row, not just the selected lot.
  const [unitCounts, setUnitCounts] = useState({});
  // Which lot `units` was actually loaded for. `units` fills in asynchronously,
  // so on a lot switch it still holds the PREVIOUS lot's records for a moment —
  // this marker is what proves a count belongs to the lot on screen.
  const [unitsLotId, setUnitsLotId] = useState('');
  const [qty, setQty] = useState(50);
  const [layout, setLayout] = useState('65');
  // Manual label size (used when layout === 'custom'): columns per row + mm.
  const [custom, setCustom] = useState({ cols: 4, w: 50, h: 30 });
  const [recallOpen, setRecallOpen] = useState(false);
  // Print scope. Defaults to 'all': the preview shows EVERY generated unit, and
  // `printed` is informational metadata — not a filter that empties the page.
  // It used to default to 'unprinted', which meant that printing a lot marked
  // its units printed and then made the whole preview (and every box card)
  // vanish, with the Print button disabled. Reprinting is a normal thing to do,
  // so the labels stay on screen and print() forces this back to 'all'.
  const [scope, setScope] = useState('all');
  // Reprint range (only used in 'all' scope): blank = all, else units fromU..toU.
  const [fromU, setFromU] = useState('');
  const [toU, setToU] = useState('');

  useEffect(() => {
    getLots().then((r) => {
      const l = listOf(r);
      setLots(l);
      // Honour ?lot=<inventoryId> (e.g. from the Lots → Label action); else first lot.
      const wanted = searchParams.get('lot');
      const match = wanted && l.find((x) => x._id === wanted);
      setLotId(match ? match._id : (l[0]?._id || ''));
    }).catch(apiError);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const lot = useMemo(() => lots.find((l) => l._id === lotId), [lots, lotId]);

  const loadUnits = () => {
    if (!lotId) return;
    // Load the FULL set (backend caps at 10000) so large lots render completely
    // and the total-count cap below stays correct; the print sheet is filtered
    // by `scope` client-side.
    // Capture the lot this fetch is for: if the user switches lots mid-flight,
    // the marker records which lot the rows that landed actually belong to.
    const forLot = lotId;
    getUnits({ inventoryId: forLot, limit: 10000 })
      .then((r) => { setUnits(listOf(r)); setUnitsLotId(forLot); })
      .catch(apiError);
  };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { loadUnits(); }, [lotId]);

  // Per-lot label counts for the whole dropdown. Refreshed after every generate
  // so the row the operator just worked on updates with the rest.
  const loadUnitCounts = () => {
    getUnitCounts()
      .then((r) => setUnitCounts(r?.data || {}))
      .catch(() => setUnitCounts({}));
  };
  useEffect(() => { loadUnitCounts(); }, []);

  // Load the lot's boxes alongside its units. A lot with no bulk packaging
  // simply returns none, so `boxes` stays empty and every branch below falls
  // back to the original single-grid behaviour.
  useEffect(() => {
    if (!lotId) { setBoxes([]); setMainBoxes([]); setTotalBoxes(null); return; }
    let cancelled = false;
    getBulkPackages(lotId)
      .then((r) => {
        if (cancelled) return;
        setBoxes(listOf(r));
        setMainBoxes(Array.isArray(r?.mainBoxes) ? r.mainBoxes : []);
        // What "Box 2 of 4" counts against — the lot's own box total, which the
        // receiving row does not carry itself. See lotController.listBulkPackages.
        setTotalBoxes(Number.isFinite(r?.totalBoxes) ? r.totalBoxes : null);
      })
      .catch(() => { if (!cancelled) { setBoxes([]); setMainBoxes([]); setTotalBoxes(null); } });
    return () => { cancelled = true; };
  }, [lotId]);

  const generate = async () => {
    if (!canGenerate) return;
    try {
      const r = await generateUnits({ inventoryId: lotId, qty: Number(qty) });
      toast('success', r?.message || 'Generated'); loadUnits(); loadUnitCounts();
    } catch (err) { apiError(err); }
  };

  const print = async () => {
    window.print();
    // Record the print for audit/history — best-effort, and deliberately
    // WITHOUT hiding anything: the sheet stays exactly as it is so the operator
    // can run it again (a jammed printer, a second copy for the carton, …).
    // Forcing 'all' guarantees the reload can't leave an empty preview.
    setScope('all');
    const serials = units.filter((u) => !u.printed).map((u) => u.serial);
    if (serials.length) { try { await markUnitsPrinted(serials); loadUnits(); } catch { /* ignore */ } }
  };

  // Resolve the active grid config. 'custom' reads the manual inputs (clamped to
  // sane minimums); presets come straight from LAYOUTS. Barcode height scales
  // with the label height so custom sizes flow through automatically.
  const cfg = layout === 'custom'
    ? { cols: Math.max(1, Number(custom.cols) || 1),
        w: Math.max(10, Number(custom.w) || 10),
        h: Math.max(8, Number(custom.h) || 8),
        label: 'Custom' }
    : LAYOUTS[layout];
  const bcH = Math.max(16, Math.round(cfg.h * 0.7));
  /**
   * Unit labels still to be generated for a lot:
   *   original lot quantity − unit labels already generated
   *
   * The selected lot uses the units this page has loaded (freshest); every
   * other row uses the per-lot aggregate. Nothing here reads warehouse stock —
   * see lotOriginalQty.
   */
  const labelsLeftFor = (l) => {
    const done = String(l?._id) === String(unitsLotId)
      ? units.length
      : (unitCounts[String(l?._id)] || 0);
    return Math.max(0, lotOriginalQty(l) - done);
  };

  /**
   * Dropdown row — deliberately compact and single-line:
   *   {Product Name} · {Lot Number} (avail {labels still to generate})
   *
   * "avail" here means UNIT LABELS LEFT TO GENERATE, not stock on hand. It used
   * to read Inventory.availableStock, which is why a lot the warehouse hadn't
   * received yet showed "avail 0".
   */
  const lotLabel = (l) =>
    `${l.productId?.productName || 'Item'} · ${l.lotNumber || l.batchNumber}`
    + ` (avail ${labelsLeftFor(l).toLocaleString('en-IN')})`;

  const qtyNum = Number(qty) || 0;
  // GENERATE availability — how many NEW labels may still be minted.
  const remaining = lot ? Math.max(0, lotOriginalQty(lot) - units.length) : 0;
  const overCap = !!lot && qtyNum > remaining;
  // Every physical unit of the lot is already labelled — nothing left to mint
  // (the operator can still reprint from here, and recall still works).
  const fullyLabelled = !!lot && remaining === 0;
  // PRINT availability — an entirely separate question: does this lot have any
  // generated label at all? Printed-before, avail 0 and printed:true are all
  // irrelevant here; reprinting is a normal operation.
  const canPrint = unitsLotId === lotId && units.length > 0;

  /**
   * AUTO-FILL the generate quantity with everything still unlabelled, so the
   * field always matches the "(avail N)" the dropdown shows for the selected
   * lot. Applies to EVERY company-side lot — it used to be gated on `isBoxed`,
   * which is why a plain lot kept showing the stale default.
   *
   * It runs when the selection changes and when `remaining` moves (units loaded,
   * or a fresh batch just generated) — never on a keystroke, because `remaining`
   * is derived from the lot and its units, not from `qty`. So the operator can
   * still type a smaller number and generate a partial batch.
   *
   * Skipped for a warehouse role: there the field is not an input at all, it is
   * a read-only display of the lot's existing unit count.
   */
  useEffect(() => {
    if (isWarehouse) return;
    if (!lotId || unitsLotId !== lotId) return;
    setQty(String(remaining));
  }, [isWarehouse, lotId, unitsLotId, remaining]);

  // CHILD UNIT COUNT for the selected parent lot — the real UnitSerial records
  // (UnitSerial.inventoryId === this lot's Inventory _id, the schema's parent-lot
  // relation), which is exactly what `units` holds. Never derived from the lot's
  // quantity, the dropdown text, the printed count or the page size.
  // null while the rows on hand belong to a different lot (i.e. still loading),
  // so a switch can never show lot A's count against lot B. 0 is a real answer:
  // a lot with no child units.
  const unitCount = unitsLotId === lotId ? units.length : null;
  // A Company Warehouse never mints serials — see GENERATE_LOCKED_MSG. This also
  // covers the generate() handler itself (it early-returns on !canGenerate), so
  // the action is unreachable even if the button's disabled state is bypassed.
  const canGenerate = !isWarehouse && !!lotId && qtyNum >= 1 && !overCap && remaining > 0;

  // Numeric sequence from a serial (<lot>-<seq>). Serials are zero-padded to
  // 3 digits, so a TEXT sort puts "…-1000" before "…-997"; we sort numerically.
  const seqNum = (serial) => parseInt(String(serial).split('-').pop(), 10) || 0;

  // What actually prints: in 'unprinted' scope only the not-yet-printed units
  // (so it continues from the next number); in 'all' scope every unit (reprint),
  // optionally narrowed to a fromU..toU range. Always in TRUE numeric order.
  const visibleUnits = useMemo(() => {
    const base = scope === 'unprinted' ? units.filter((u) => !u.printed) : units;
    let list = [...base].sort((a, b) => seqNum(a.serial) - seqNum(b.serial));
    if (scope === 'all' && (fromU !== '' || toU !== '')) {
      const lo = fromU !== '' ? Number(fromU) : -Infinity;
      const hi = toU !== '' ? Number(toU) : Infinity;
      list = list.filter((u) => { const n = seqNum(u.serial); return n >= lo && n <= hi; });
    }
    return list;
  }, [units, scope, fromU, toU]);
  // first/last unit number on the sheet (visibleUnits is sorted ascending).
  const seqRange = visibleUnits.length
    ? { first: seqNum(visibleUnits[0].serial), last: seqNum(visibleUnits[visibleUnits.length - 1].serial) }
    : null;

  /* ---- BULK PACKAGING (Lot → Box → Units) -------------------------------
     Only when the lot really has boxes. Everything below degrades to the
     original flat grid when `boxes` is empty, so a single-package lot — and
     every lot created before this feature — prints exactly as it did. */
  /**
   * THE BOXES DECIDE, not the lot row's flag.
   *
   * `has_bulk_packaging` is written by Create Lot, so it is set on the row the
   * lot was CREATED on and nowhere else. A warehouse that receives a transfer
   * gets a brand-new Inventory row without it, so this page read "not boxed" and
   * printed a flat grid of unit labels — no Bulk Packaging label, no inner box,
   * no "Units in this box" heading — for cartons the warehouse was physically
   * holding.
   *
   * If the API returned boxes, the lot IS boxed: a BulkPackage row exists only
   * for a lot that has one. A single-package lot returns none and still falls
   * through to the flat grid, exactly as before.
   */
  const isBoxed = boxes.length > 0;

  // The visible units of each box, in box order then unit order. A unit knows
  // its box through bulk_packaging_record_id (set when it was minted).
  const boxGroups = useMemo(() => {
    if (!isBoxed) return [];
    const byBox = new Map(boxes.map((b) => [String(b._id), []]));
    for (const u of visibleUnits) {
      const key = String(u.bulk_packaging_record_id || '');
      if (byBox.has(key)) byBox.get(key).push(u);
    }
    return boxes.map((b) => ({
      box: b,
      units: (byBox.get(String(b._id)) || []).sort((x, y) => (x.unit_serial || 0) - (y.unit_serial || 0)),
    }));
  }, [isBoxed, boxes, visibleUnits]);

  // Boxes with nothing to print are skipped entirely, so an unprinted-only run
  // never emits a page holding just a box label.
  const printableGroups = useMemo(() => boxGroups.filter((g) => g.units.length > 0), [boxGroups]);

  /* ---- THREE LEVELS (Lot → Main Box → Inner Box → Units) -----------------
     Only when the lot really has main box records. The parent link comes from
     the stored `parent_box_id`, never from reading the ID string: the two IDs
     share a prefix by convention, not by contract, and a lot whose numbering
     was composed differently would break any parsing rule.

     An inner box's number is its position INSIDE its main box (1…5), which the
     API resolves from the same records — its own box_serial is lot-wide (1…10)
     and would read as "box 7 of 10" on a carton that is really box 2 of 5. */
  const isNested = isBoxed && mainBoxes.length > 0;

  const mainGroups = useMemo(() => {
    if (!isNested) return [];
    const byParent = new Map(mainBoxes.map((m) => [String(m._id), []]));
    for (const g of printableGroups) {
      const key = String(g.box.parent_box_id || '');
      if (byParent.has(key)) byParent.get(key).push(g);
    }
    // A main box whose inner boxes have no labels yet is skipped, exactly as a
    // box with no labels is skipped in the flat layout.
    return mainBoxes
      .map((m) => ({ main: m, inners: byParent.get(String(m._id)) || [] }))
      .filter((n) => n.inners.length > 0);
  }, [isNested, mainBoxes, printableGroups]);

  // Packaging shape of a boxed lot. boxes × units-per-box always EQUALS the
  // lot's original quantity — lotService enforces that identity when the lot is
  // created — so the label capacity of a boxed lot is the same number as any
  // other lot's, and a warehouse's receiving progress never changes it.
  const packedTotal = isBoxed ? Number(lot.number_of_boxes) * Number(lot.units_per_box) : 0;

  return (
    <div className="flex-1 overflow-y-auto p-4 sm:p-8 bg-white font-sora">
      <style>{PRINT_CSS}</style>
      <div className="w-full max-w-[100rem] mx-auto space-y-6">
        {/* Controls */}
        <div className="no-print border border-stone-200 rounded-2xl p-4 shadow-sm space-y-3">
          <div className="flex flex-wrap items-end gap-3">
            <div className="flex-1 min-w-[220px]">
              <Field label="Lot">
                <select className={inputCls} value={lotId} onChange={(e) => setLotId(e.target.value)}>
                  {/* A fully-labelled lot stays in the list — you still print,
                      reprint and recall from here — and reads "Labels remaining 0". */}
                  {lots.map((l) => <option key={l._id} value={l._id}>{lotLabel(l)}</option>)}
                </select>
              </Field>
            </div>
            <Field label="Generate qty">
              <div className="inline-flex items-center gap-1" title={isWarehouse ? GENERATE_LOCKED_MSG : undefined}>
                <button
                  type="button"
                  onClick={() => setQty((q) => String(Math.max(1, (Number(q) || 0) - 1)))}
                  disabled={isWarehouse}
                  className="h-10 w-10 rounded-lg border border-stone-200 text-stone-600 hover:bg-stone-50 text-lg font-bold flex items-center justify-center disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-transparent"
                  title={isWarehouse ? GENERATE_LOCKED_MSG : 'Decrease'}
                >−</button>
                <input
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  className={`${inputCls} w-28 text-center disabled:bg-stone-100 disabled:text-stone-400 disabled:cursor-not-allowed`}
                  // A warehouse can't generate, so the field is repurposed as a
                  // read-out of the child units that already exist for this lot
                  // (grouped "2,800", never the "50" generate default). The main
                  // company keeps the editable generate quantity untouched.
                  value={isWarehouse
                    ? (unitCount === null ? '…' : unitCount.toLocaleString('en-IN'))
                    : qty}
                  placeholder="Qty"
                  disabled={isWarehouse}
                  title={isWarehouse ? GENERATE_LOCKED_MSG : undefined}
                  // Free typing: keep only digits; allow the field to be empty
                  // while editing. Validation/cap handled by canGenerate below.
                  onChange={(e) => setQty(e.target.value.replace(/[^0-9]/g, ''))}
                />
                <button
                  type="button"
                  onClick={() => setQty((q) => String(Math.min(remaining || 1, (Number(q) || 0) + 1)))}
                  disabled={isWarehouse}
                  className="h-10 w-10 rounded-lg border border-stone-200 text-stone-600 hover:bg-stone-50 text-lg font-bold flex items-center justify-center disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-transparent"
                  title={isWarehouse ? GENERATE_LOCKED_MSG : 'Increase'}
                >+</button>
              </div>
            </Field>
            <PrimaryBtn
              onClick={generate}
              disabled={!canGenerate}
              title={isWarehouse
                ? GENERATE_LOCKED_MSG
                : (fullyLabelled ? ALL_LABELLED_MSG : undefined)}
            >
              <span className="material-symbols-outlined text-base">qr_code_2</span> Generate Units
            </PrimaryBtn>
          </div>

          {/* Label capacity: the lot's ORIGINAL created quantity, never live
              stock. A warehouse can't generate at all, so it reads the count
              without the cap advice. */}
          {lot && (
            isWarehouse ? (
              <p className="text-[11px] text-stone-400">
                {units.length.toLocaleString('en-IN')} of {lotOriginalQty(lot).toLocaleString('en-IN')} unit(s) in this lot already labelled — {GENERATE_LOCKED_MSG}
              </p>
            ) : (
              <p className={`text-[11px] ${overCap ? 'text-[#EA2831] font-semibold' : 'text-stone-400'}`}>
                {units.length.toLocaleString('en-IN')} of {lotOriginalQty(lot).toLocaleString('en-IN')} unit(s) in this lot already labelled —{' '}
                {remaining > 0
                  ? <>you can generate up to <b>{remaining.toLocaleString('en-IN')}</b> more.{overCap && ' Reduce the quantity.'}</>
                  : <b className="text-stone-500">{ALL_LABELLED_MSG}</b>}
              </p>
            )
          )}

          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-2 text-sm">
              {/* <span className="text-stone-400">{units.length} unit(s) generated</span> */}
              {/* <select className="border border-stone-200 rounded-lg text-xs px-2 py-1.5 bg-white" value={scope} onChange={(e) => setScope(e.target.value)} title="Which labels to print">
                <option value="unprinted">Unprinted only</option>
                <option value="all">All units</option>
              </select> */}
              <select className="border border-stone-200 rounded-lg text-xs px-2 py-1.5 bg-white" value={layout} onChange={(e) => setLayout(e.target.value)}>
                {Object.entries(LAYOUTS).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}
                <option value="custom">Custom size…</option>
              </select>
              {layout === 'custom' && (
                <div className="no-print flex items-center gap-2">
                  {[
                    ['Cols', 'cols', 1],
                    ['Width (mm)', 'w', 10],
                    ['Height (mm)', 'h', 8],
                  ].map(([lbl, key, min]) => (
                    <label key={key} className="flex flex-col text-[10px] font-bold uppercase tracking-wider text-stone-400">
                      {lbl}
                      <input
                        type="number" min={min}
                        className="mt-0.5 w-16 border border-stone-200 rounded-lg text-xs px-2 py-1.5 bg-white text-stone-700"
                        value={custom[key]}
                        onChange={(e) => setCustom((c) => ({ ...c, [key]: e.target.value }))}
                      />
                    </label>
                  ))}
                </div>
              )}
            </div>
            <div className="flex items-center gap-2">
              {/* {canRecall && lot && <GhostBtn onClick={() => setRecallOpen(true)}>Recall this lot</GhostBtn>} */}
              {/* PRINT and GENERATE are separate capabilities:
                    canGenerate → is there anything left to MINT? (avail > 0)
                    canPrint    → does this lot have ANY generated label?
                  A lot at "avail 0" is fully labelled, which is precisely when
                  you want to print — so printing must never be gated on the
                  generate cap, nor on whether the labels were printed before. */}
              <PrimaryBtn onClick={print} disabled={!canPrint} title={canPrint ? undefined : 'Generate unit labels first.'}>
                <span className="material-symbols-outlined text-base">print</span> Print Labels
              </PrimaryBtn>
            </div>
          </div>

          {/* Reprint range — only when reprinting (All units). */}
          {/* {scope === 'all' && (
            <div className="flex flex-wrap items-end gap-2 border-t border-stone-100 pt-3">
              <Field label="From unit #">
                <input type="text" inputMode="numeric" pattern="[0-9]*" className={`${inputCls} w-28`} value={fromU}
                  onChange={(e) => setFromU(e.target.value.replace(/[^0-9]/g, ''))} placeholder="e.g. 1000" />
              </Field>
              <Field label="To unit #">
                <input type="text" inputMode="numeric" pattern="[0-9]*" className={`${inputCls} w-28`} value={toU}
                  onChange={(e) => setToU(e.target.value.replace(/[^0-9]/g, ''))} placeholder="e.g. 1600" />
              </Field>
              {(fromU !== '' || toU !== '') && (
                <button type="button" onClick={() => { setFromU(''); setToU(''); }} className="text-[11px] font-bold text-[#EA2831] hover:underline pb-2.5">Clear</button>
              )}
              <p className="basis-full text-[11px] text-stone-400">
                Leave blank to reprint all, or enter a range (e.g. 1000–1600) to reprint specific units you missed.
              </p>
            </div>
          )} */}
        </div>

        {/* Helper: what's about to print (outside #label-sheet, so it isn't printed). */}
        {/* {lot && visibleUnits.length > 0 && (
          <p className="no-print text-[11px] text-stone-500">
            Printing <b>{visibleUnits.length.toLocaleString('en-IN')}</b> label(s)
            {isNested
              ? <> — the lot label prints on its own sheet, then <b>{mainGroups.length}</b> bulk packaging box page(s) and the <b>{printableGroups.length}</b> inner box page(s) inside them, one sheet per box. Collapsing a box on screen does not remove it from the print — every label prints.</>
              : isBoxed
                ? <> — the lot label prints on its own sheet, then <b>{printableGroups.length}</b> of {boxes.length} box page(s), one per Bulk Packaging ID. A box with no labels yet is not printed.</>
                : (seqRange ? <> (units {seqRange.first}–{seqRange.last})</> : null)}
          </p>
        )} */}

        {/* Packaging read-out: makes the Lot → Box → Unit hierarchy explicit,
            and explains where the generate quantity comes from. */}
        {/* {lot && isBoxed && (
          <div className="no-print rounded-xl border border-stone-200 bg-stone-50/60 px-4 py-3">
            <p className="text-[11px] text-stone-600">
              {isNested ? (
                <>
                  This lot is packed into <b>{mainBoxes.length} bulk packaging box(es) × {mainBoxes[0]?.inner_total || 0} inner box(es) × {Number(lot.units_per_box).toLocaleString('en-IN')} units</b> = {packedTotal.toLocaleString('en-IN')} unit label(s).
                  Every level carries its own barcode: the bulk packaging box, each inner box inside it, and each unit inside an inner box.
                </>
              ) : (
                <>
                  This lot is packed into <b>{lot.number_of_boxes} box(es) × {Number(lot.units_per_box).toLocaleString('en-IN')} units</b> = {packedTotal.toLocaleString('en-IN')} unit label(s).
                  Unit codes descend from each box’s Bulk Packaging ID.
                </>
              )}
            </p>
            <p className="text-[11px] text-stone-400 mt-1">
              {units.length.toLocaleString('en-IN')} of {lotOriginalQty(lot).toLocaleString('en-IN')} unit(s) labelled.
              Units fill the boxes in order — the first box first, then the next, and so on.
            </p>
          </div>
        )} */}

        {/* Printable label sheet.
            THREE DISTINCT BARCODES, never substituted for one another:
              Lot Label            → encodes the LOT NUMBER
              Bulk Packaging Label → encodes the BULK PACKAGING ID
              Unit label           → encodes the UNIT CODE
            The Lot Label is the sheet's MASTER label, rendered once at the top;
            the Bulk Packaging Label is an addition per box, never a
            replacement for it. */}
        <div id="label-sheet" className={isNested ? 'nested-sheet' : undefined}>
          {/* MASTER LOT LABEL — once for the whole sheet, centred, OUTSIDE the
              box page cards. It is the lot's common identity, so repeating it
              inside every box card would just be noise. Shown for both a boxed
              and a single-package lot. */}
          {lot && (
            <div
              className={`lot-master label-block${!isNested && isBoxed && printableGroups.length ? ' has-pages' : ''}`}
              style={{ maxWidth: `${TOP_CARD_W}px` }}
            >
              <LotLabel lot={lot} />
            </div>
          )}

          {isNested ? (
            /* THREE LEVELS — one card per MAIN bulk packaging box, with its own
               inner box cards nested INSIDE its border. An inner box never
               appears at the top level: the top level is the outer carton the
               warehouse actually moves, and the inner boxes are what is found
               when that carton is opened.

               Each card is one printed sheet (see .nested-sheet in PRINT_CSS),
               in document order: main box, then its inner boxes and their
               units, then the next main box. */
            <div className="bp-grid" style={{ gridTemplateColumns: '1fr' }}>
              {mainGroups.map(({ main, inners }) => (
                <section key={main.bulk_packaging_id} className="main-card">
                  <div className="bp-page flex flex-col items-center">
                    {/* <p className="text-center text-[11px] font-bold uppercase tracking-widest text-stone-500 mb-2">
                      Bulk Packaging Box {main.main_serial} of {main.total}
                    </p> */}
                    {/* Same width as the lot label above it, so the Lot: line
                        no longer wraps mid-ID. width:100% is what lets it grow
                        to that cap — the card is a flex item under
                        items-center, where a bare max-width would leave it
                        shrink-to-fit. Centring comes from that same flex. */}
                    <div className="label-block w-full" style={{ maxWidth: `${TOP_CARD_W}px` }}>
                      <BulkPackageLabel
                        box={main}
                        lot={lot}
                        caption={`Bulk Packaging Box ${main.main_serial} of ${main.total}`}
                      />
                    </div>
                    {/* <p className="no-print text-center text-[11px] text-stone-400 mt-2">
                      Contains {inners.length} inner box(es).
                    </p> */}
                  </div>

                  <div className="inner-stack grid grid-cols-2 gap-4">
                    {inners.map(({ box, units: boxUnits }) => {
                      const caption = `Inner Box ${box.inner_index} of ${main.inner_total}`;
                      return (
                        <section key={box.bulk_packaging_id} className="bp-page inner-card flex flex-col items-center">
                          {/* <p className="text-center text-[11px] font-bold uppercase tracking-widest text-stone-500 mb-2">
                            {caption}
                          </p> */}
                          <div className="label-block" style={{ maxWidth: `${rowWidthMm(BOX_UNIT_COLS, cfg.w)}mm` }}>
                            <BulkPackageLabel box={box} lot={lot} caption={caption} />
                          </div>

                          {/* THE UNITS OF *THIS* INNER BOX. `boxUnits` comes
                              from boxGroups, which keys every unit on its own
                              bulk_packaging_record_id — the inner box that holds
                              it — so a card never shows the lot's or the main
                              box's units. Same grid and header as the two-level
                              layout below. */}
                          <p className="text-center text-[11px] font-bold uppercase tracking-widest text-stone-400 mt-4 mb-2">
                            Units in this box — {boxUnits.length}
                          </p>
                          <UnitGrid units={boxUnits} lot={lot} cfg={cfg} bcH={bcH} boxed cols={BOX_UNIT_COLS} />
                        </section>
                      );
                    })}
                  </div>
                </section>
              ))}
            </div>
          ) : isBoxed ? (
            /* BULK PACKAGING — one card per physical box. Side by side on
               screen (see .bp-grid), one per sheet in print. Each card holds
               ONLY what differs between boxes: the box label, its barcode and
               its own units. */
            <div
              className="bp-grid"
              style={{
                // ONE rule for every card count — a card is never given a
                // special width just because it happens to be the only one
                // visible. A track is at least as wide as a 3-label unit row
                // plus its padding, so the unit grid inside never overflows;
                // auto-fit then packs as many cards per row as the viewport
                // allows (2 on a desktop) and drops to a single column on a
                // narrow screen or at high zoom, where min(100%, …) keeps the
                // card inside the viewport.
                gridTemplateColumns: `repeat(auto-fit, minmax(min(100%, ${rowWidthMm(BOX_UNIT_COLS, cfg.w) + 12}mm), 1fr))`,
              }}
            >
              {printableGroups.map(({ box, units: boxUnits }) => (
                <section key={box.bulk_packaging_id} className="bp-page print-page">
                  {/* Same width as the unit row beneath it, so the box label
                      and its units line up as one column on screen AND on the
                      printed sheet (where the card itself is full width). */}
                  <div className="label-block" style={{ maxWidth: `${rowWidthMm(BOX_UNIT_COLS, cfg.w)}mm` }}>
                    <BulkPackageLabel box={box} lot={lot} totalBoxes={totalBoxes ?? lot.number_of_boxes} />
                  </div>

                  <p className="text-center text-[11px] font-bold uppercase tracking-widest text-stone-400 mt-4 mb-2">
                    Units in this box — {boxUnits.length}
                  </p>

                  <UnitGrid units={boxUnits} lot={lot} cfg={cfg} bcH={bcH} boxed cols={BOX_UNIT_COLS} />
                </section>
              ))}
            </div>
          ) : (
            /* NO BULK PACKAGING — the original layout: the lot label above (the
               master block), then the unit labels at the selected paper size.
               No box label, no per-box pages. */
            <UnitGrid units={visibleUnits} lot={lot} cfg={cfg} bcH={bcH} />
          )}
          {visibleUnits.length === 0 && (
            <p className="no-print text-sm text-stone-400 py-10 text-center">
              {units.length === 0
                ? 'No units yet — generate some to print labels.'
                : scope === 'unprinted'
                  // Only reachable if the (currently hidden) scope selector is
                  // put back and switched away from "All units".
                  ? 'All units are already printed. Switch to “All units” to reprint.'
                  : 'No units match that range. Clear the range to see every label.'}
            </p>
          )}
        </div>
      </div>

      {recallOpen && lot && (
        <RecallModal lot={lot} onClose={() => setRecallOpen(false)} onDone={() => { setRecallOpen(false); loadUnits(); }} />
      )}
    </div>
  );
};

const RecallModal = ({ lot, onClose, onDone }) => {
  const [result, setResult] = useState(null);
  const [busy, setBusy] = useState(false);
  const run = async () => {
    const ok = await Swal.fire({ icon: 'warning', title: `Recall lot ${lot.lotNumber || lot.batchNumber}?`, text: 'All not-yet-sold units will be blocked from picking.', showCancelButton: true, confirmButtonColor: '#EA2831' });
    if (!ok.isConfirmed) return;
    setBusy(true);
    try { const r = await recallLot(lot.lotNumber || lot.batchNumber); setResult(r?.data); toast('success', r?.message || 'Recalled'); }
    catch (err) { apiError(err); } finally { setBusy(false); }
  };
  return (
    <Modal title="Recall Lot" onClose={onClose} wide>
      {!result ? (
        <>
          <p className="text-sm text-stone-600 mb-4">This blocks all not-yet-sold units of <b>{lot.lotNumber || lot.batchNumber}</b> and lists everywhere the lot has reached.</p>
          <PrimaryBtn disabled={busy} onClick={run}>{busy ? 'Recalling…' : 'Execute Recall'}</PrimaryBtn>
        </>
      ) : (
        <div className="space-y-4 text-sm">
          <div className="flex gap-4">
            <div className="bg-red-50 text-red-700 rounded-lg px-3 py-2 font-bold">{result.recalledUnits} recalled</div>
            <div className="bg-amber-50 text-amber-700 rounded-lg px-3 py-2 font-bold">{result.soldUnits} already sold</div>
          </div>
          <div>
            <p className="font-bold text-stone-700 mb-1">Stock still held</p>
            {result.stock?.map((s, i) => (
              <div key={i} className="text-xs text-stone-500 border-b border-dashed border-stone-100 py-1">
                {s.warehouse}: avail {s.availableStock}, damaged {s.damagedStock}
                {s.bins?.length > 0 && <span className="ml-2 font-mono">[{s.bins.map((b) => `${b.bin}:${b.qty}`).join(', ')}]</span>}
              </div>
            ))}
          </div>
          <div>
            <p className="font-bold text-stone-700 mb-1">Customers / orders reached</p>
            {result.customers?.length ? result.customers.map((c, i) => (
              <div key={i} className="text-xs text-stone-500 py-0.5">{c.orderNumber} · {c.customerName || '—'}</div>
            )) : <p className="text-xs text-stone-400">None recorded.</p>}
          </div>
          <PrimaryBtn onClick={onDone}>Done</PrimaryBtn>
        </div>
      )}
    </Modal>
  );
};

export default ImsLabels;